### ISSUE TITLE
AWS Health SHD Notifier - How to run the deploy.sh script

### ISSUE THREAD

**Issue by djl2** [aws/aws-health-tools#76]
Regarding AWS Health SHD Notifier installation--

Perhaps this is a basic question, but could you please provide details for running the deploy.sh script after the Cloudformation installation step?  I've already cloned the git repo locally and have the aws cli installed/configured on Win10.  Thank you.

**Comment by AWSjcwalp** [comment]
The purpose of the script is to deploy the Lambda code to the relevant functions, which due to size limitations, cannot be included in the CloudFormation template.

The deploy.sh script was written for Linux, but can be run in Windows by installing Windows Subsystem for Linux and then executing the command: 
`bash deploy.sh`

Alternatively, you can zip each Python script specified in `deploy.sh` and use the AWS CLI to update the corresponding Lambda function with the zipped file.

**Comment by djl2** [comment]
Thanks!
